services:
  - type: worker
    name: tv-trade-poster-worker
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: VERCEL_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: WEBSOCKET_URL
        sync: false
      - key: SOCKET_TOKEN
        sync: false
